# Generated by Django 6.0.4 on 2026-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', '대기'), ('entered', '입장'), ('exited', '퇴장')], db_index=True, default='waiting', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='iomanager_app.customer')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
