# Generated by Django 6.0.4 on 2026-04-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('issue_count', models.PositiveIntegerField(default=1)),
                ('valid_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_count', models.PositiveIntegerField(default=0)),
                ('expires_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='iomanager_app.customer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_passes', to='iomanager_app.passtemplate')),
            ],
            options={
                'ordering': ['expires_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PassTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('issued', '발행'), ('used', '사용')], db_index=True, max_length=10)),
                ('happened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_transactions', to='iomanager_app.customer')),
                ('customer_pass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='iomanager_app.customerpass')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='iomanager_app.passtemplate')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_transactions', to='iomanager_app.visitsession')),
            ],
            options={
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_items', to='iomanager_app.producttemplate')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='iomanager_app.visitsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
