# Generated by Django 6.0.4 on 2026-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0002_passtemplate_producttemplate_customerpass_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_visit_at', 'id'], name='customer_last_visit_id_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpass',
            index=models.Index(fields=['expires_on', 'id'], name='customerpass_expires_id_idx'),
        ),
        migrations.AddIndex(
            model_name='passtransaction',
            index=models.Index(fields=['happened_at', 'id'], name='passtrx_happened_id_idx'),
        ),
        migrations.AddIndex(
            model_name='visitsession',
            index=models.Index(fields=['requested_at', 'id'], name='visit_requested_id_idx'),
        ),
    ]
