# Generated by Django 6.0.4 on 2026-04-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0003_customer_customer_last_visit_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitsession',
            name='re_wait_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
