# Generated by Django 6.0.4 on 2026-04-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0004_visitsession_re_wait_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passtransaction',
            name='status',
            field=models.CharField(choices=[('issued', '발행'), ('used', '사용'), ('expired', '만료')], db_index=True, max_length=10),
        ),
    ]
