# Generated by Django 6.0.4 on 2026-04-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0005_alter_passtransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
