# Generated by Django 6.0.4 on 2026-04-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0006_passtemplate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passtemplate',
            name='is_active',
        ),
        migrations.AddField(
            model_name='passtransaction',
            name='template_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passtransaction',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='iomanager_app.passtemplate'),
        ),
    ]
