# Generated by Django 6.0.4 on 2026-04-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iomanager_app', '0008_backfill_template_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_items', to='iomanager_app.producttemplate'),
        ),
    ]
